<a href="https://colab.research.google.com/github/aliprg0/Google_Colab/blob/main/AMP_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install yfinance
!pip install yahooquery
!pip install tvdatafeed
from tvDatafeed import TvDatafeed, Interval
from yahooquery import Screener
import yfinance as yf   
import pandas as pd
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
import random 
from tensorflow.keras.models import load_model
import os
import shutil
from datetime import datetime
import glob

In [7]:
def scaler(row):
    scaler = MinMaxScaler(feature_range=(0, 1))
    row = scaler.fit_transform(row)
    return row

In [238]:
#Monthly-3
model = load_model("/content/drive/MyDrive/Exported Models/monthly_crypto_96_xbv85.h5")
def process_for_prediction(data):
    i = -1
    row = []
    if len(pd.DataFrame(data).columns) == 7:
      data = data.iloc[: , 1:]        
    data = np.array(data)
    grow = []
      
    s12 = [ 
            data[i-12][0], data[i-12][1], data[i-12][2], data[i-12][3]
        ]
    s11 = [
            data[i-11][0], data[i-11][1], data[i-11][2], data[i-11][3]
        ]
    s10 = [
            data[i-10][0], data[i-10][1], data[i-10][2], data[i-10][3]
        ]
    s9 = [
            data[i-9][0], data[i-9][1], data[i-9][2], data[i-9][3]
        ]
    s8 = [
            data[i-8][0], data[i-8][1], data[i-8][2], data[i-8][3]
        ]
    s7 = [
            data[i-7][0], data[i-7][1], data[i-7][2], data[i-7][3]
        ]
    s6 = [
            data[i-6][0], data[i-6][1], data[i-6][2], data[i-6][3]
        ]
    s5 = [
            data[i-5][0], data[i-5][1], data[i-5][2], data[i-5][3]
        ]   
    s4 = [
            data[i-4][0], data[i-4][1], data[i-4][2], data[i-4][3]
        ]
    s3 = [
            data[i-3][0], data[i-3][1], data[i-3][2], data[i-3][3]
        ]
    s2 = [
            data[i-2][0], data[i-2][1], data[i-2][2], data[i-2][3]
        ]
    s1 = [
            data[i-1][0], data[i-1][1], data[i-1][2], data[i-1][3]
        ]
        

    s1 = scaler(np.array(s1).reshape(-1,1))
    s2 = scaler(np.array(s2).reshape(-1,1))
    s3 = scaler(np.array(s3).reshape(-1,1))
    s4 = scaler(np.array(s4).reshape(-1,1))
    s5 = scaler(np.array(s5).reshape(-1,1))
    s6 = scaler(np.array(s6).reshape(-1,1))
    s7 = scaler(np.array(s7).reshape(-1,1))
    s8 = scaler(np.array(s8).reshape(-1,1))
    s9 = scaler(np.array(s9).reshape(-1,1))
    s10 = scaler(np.array(s10).reshape(-1,1))
    s11 = scaler(np.array(s11).reshape(-1,1))
    s12 = scaler(np.array(s12).reshape(-1,1))
    
    s1 = np.delete(s1, 1)
    s1 = np.delete(s1, 1)
    s2 = np.delete(s2, 1)
    s2 = np.delete(s2, 1)
    s3 = np.delete(s3, 1)
    s3 = np.delete(s3, 1)
    s4 = np.delete(s4, 1)
    s4 = np.delete(s4, 1)
    s5 = np.delete(s5, 1)
    s5 = np.delete(s5, 1)
    s6 = np.delete(s6, 1)
    s6 = np.delete(s6, 1)
    s7 = np.delete(s7, 1)
    s7 = np.delete(s7, 1)
    s8 = np.delete(s8, 1)
    s8 = np.delete(s8, 1)
    s9 = np.delete(s9, 1)
    s9 = np.delete(s9, 1)
    s10 = np.delete(s10, 1)
    s10 = np.delete(s10, 1)
    s11 = np.delete(s11, 1)
    s11 = np.delete(s11, 1)
    s12 = np.delete(s12, 1)
    s12 = np.delete(s12, 1)
            
        

    grow = np.vstack((s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12))

    arr = np.array(grow).flatten()
    row.append(arr)

    return np.array(row)
def make_prediction(symbol,timeframe):
  if timeframe == "5m":
    data = yf.download(symbol,period="1d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))    
  if timeframe == "15m":
    data = yf.download(symbol,period="1d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "1h":
    data = yf.download(symbol,period="1d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "1d":
    data = yf.download(symbol,period="20d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "1wk":
    data = yf.download(symbol,period="max",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "1mo":
    data = yf.download(symbol,period="max",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "1m":
    data = yf.download(symbol,period="1d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "2m":
    data = yf.download(symbol,period="max",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "30m":
    data = yf.download(symbol,period="1d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "5d":
    data = yf.download(symbol,period="5mo",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "90m":
    data = yf.download(symbol,period="5d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "3mo":
    data = yf.download(symbol,period="max",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))

In [239]:
make_prediction("btc-usd","15m")

[*********************100%***********************]  1 of 1 completed

array([[0.25566906, 0.692947  ]], dtype=float32)

In [240]:
def process_for_prediction(data):
    i = -1
    row = []
    data.drop("symbol",axis=1,inplace=True)   
    data = np.array(data)
    llst = [0, 1, 2, 3, 4]
    grow = []
      
    s12 = [ 
            data[i-12][0], data[i-12][1], data[i-12][2], data[i-12][3]
        ]
    s11 = [
            data[i-11][0], data[i-11][1], data[i-11][2], data[i-11][3]
        ]
    s10 = [
            data[i-10][0], data[i-10][1], data[i-10][2], data[i-10][3]
        ]
    s9 = [
            data[i-9][0], data[i-9][1], data[i-9][2], data[i-9][3]
        ]
    s8 = [
            data[i-8][0], data[i-8][1], data[i-8][2], data[i-8][3]
        ]
    s7 = [
            data[i-7][0], data[i-7][1], data[i-7][2], data[i-7][3]
        ]
    s6 = [
            data[i-6][0], data[i-6][1], data[i-6][2], data[i-6][3]
        ]
    s5 = [
            data[i-5][0], data[i-5][1], data[i-5][2], data[i-5][3]
        ]   
    s4 = [
            data[i-4][0], data[i-4][1], data[i-4][2], data[i-4][3]
        ]
    s3 = [
            data[i-3][0], data[i-3][1], data[i-3][2], data[i-3][3]
        ]
    s2 = [
            data[i-2][0], data[i-2][1], data[i-2][2], data[i-2][3]
        ]
    s1 = [
            data[i-1][0], data[i-1][1], data[i-1][2], data[i-1][3]
        ]
        

    s1 = scaler(np.array(s1).reshape(-1,1))
    s2 = scaler(np.array(s2).reshape(-1,1))
    s3 = scaler(np.array(s3).reshape(-1,1))
    s4 = scaler(np.array(s4).reshape(-1,1))
    s5 = scaler(np.array(s5).reshape(-1,1))
    s6 = scaler(np.array(s6).reshape(-1,1))
    s7 = scaler(np.array(s7).reshape(-1,1))
    s8 = scaler(np.array(s8).reshape(-1,1))
    s9 = scaler(np.array(s9).reshape(-1,1))
    s10 = scaler(np.array(s10).reshape(-1,1))
    s11 = scaler(np.array(s11).reshape(-1,1))
    s12 = scaler(np.array(s12).reshape(-1,1))
    
    s1 = np.delete(s1, 1)
    s1 = np.delete(s1, 1)
    s2 = np.delete(s2, 1)
    s2 = np.delete(s2, 1)
    s3 = np.delete(s3, 1)
    s3 = np.delete(s3, 1)
    s4 = np.delete(s4, 1)
    s4 = np.delete(s4, 1)
    s5 = np.delete(s5, 1)
    s5 = np.delete(s5, 1)
    s6 = np.delete(s6, 1)
    s6 = np.delete(s6, 1)
    s7 = np.delete(s7, 1)
    s7 = np.delete(s7, 1)
    s8 = np.delete(s8, 1)
    s8 = np.delete(s8, 1)
    s9 = np.delete(s9, 1)
    s9 = np.delete(s9, 1)
    s10 = np.delete(s10, 1)
    s10 = np.delete(s10, 1)
    s11 = np.delete(s11, 1)
    s11 = np.delete(s11, 1)
    s12 = np.delete(s12, 1)
    s12 = np.delete(s12, 1)
        

    grow = np.vstack((s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12))

    arr = np.array(grow).flatten()
    row.append(arr)

    return np.array(row)
def make_prediction(symbol,timeframe):
   tv = TvDatafeed()
   data = tv.get_hist(symbol='btcusdt',exchange='binance',interval=Interval.in_15_minute,n_bars=30)
   return model.predict(process_for_prediction(data))

In [241]:
make_prediction("s","x")

WARNING:tvDatafeed.main:you are using nologin method, data you access may be limited

array([[0.12591091, 0.8319332 ]], dtype=float32)

In [242]:
#cfm weeky 94
model = load_model("/content/drive/MyDrive/Exported Models/weekly_crypto_94_jako6.h5")
def process_for_prediction(data):
    i = -1
    row = []
    if len(pd.DataFrame(data).columns) == 7:
      data = data.iloc[: , 1:]        
    data = np.array(data)
    grow = []
      
    s12 = [ 
            data[i-12][0], data[i-12][1], data[i-12][2], data[i-12][3]
        ]
    s11 = [
            data[i-11][0], data[i-11][1], data[i-11][2], data[i-11][3]
        ]
    s10 = [
            data[i-10][0], data[i-10][1], data[i-10][2], data[i-10][3]
        ]
    s9 = [
            data[i-9][0], data[i-9][1], data[i-9][2], data[i-9][3]
        ]
    s8 = [
            data[i-8][0], data[i-8][1], data[i-8][2], data[i-8][3]
        ]
    s7 = [
            data[i-7][0], data[i-7][1], data[i-7][2], data[i-7][3]
        ]
    s6 = [
            data[i-6][0], data[i-6][1], data[i-6][2], data[i-6][3]
        ]
    s5 = [
            data[i-5][0], data[i-5][1], data[i-5][2], data[i-5][3]
        ]   
    s4 = [
            data[i-4][0], data[i-4][1], data[i-4][2], data[i-4][3]
        ]
    s3 = [
            data[i-3][0], data[i-3][1], data[i-3][2], data[i-3][3]
        ]
    s2 = [
            data[i-2][0], data[i-2][1], data[i-2][2], data[i-2][3]
        ]
    s1 = [
            data[i-1][0], data[i-1][1], data[i-1][2], data[i-1][3]
        ]
        

    s1 = scaler(np.array(s1).reshape(-1,1))
    s2 = scaler(np.array(s2).reshape(-1,1))
    s3 = scaler(np.array(s3).reshape(-1,1))
    s4 = scaler(np.array(s4).reshape(-1,1))
    s5 = scaler(np.array(s5).reshape(-1,1))
    s6 = scaler(np.array(s6).reshape(-1,1))
    s7 = scaler(np.array(s7).reshape(-1,1))
    s8 = scaler(np.array(s8).reshape(-1,1))
    s9 = scaler(np.array(s9).reshape(-1,1))
    s10 = scaler(np.array(s10).reshape(-1,1))
    s11 = scaler(np.array(s11).reshape(-1,1))
    s12 = scaler(np.array(s12).reshape(-1,1))

        

    grow = np.vstack((s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12))

    arr = np.array(grow).flatten()
    row.append(arr)

    return np.array(row)
def make_prediction(symbol,timeframe):
  if timeframe == "5m":
    data = yf.download(symbol,period="1d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))    
  if timeframe == "15m":
    data = yf.download(symbol,period="1d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "1h":
    data = yf.download(symbol,period="1d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "1d":
    data = yf.download(symbol,period="20d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "1wk":
    data = yf.download(symbol,period="max",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "1mo":
    data = yf.download(symbol,period="max",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "1m":
    data = yf.download(symbol,period="1d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "2m":
    data = yf.download(symbol,period="max",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "30m":
    data = yf.download(symbol,period="1d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "5d":
    data = yf.download(symbol,period="5mo",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "90m":
    data = yf.download(symbol,period="5d",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))  
  if timeframe == "3mo":
    data = yf.download(symbol,period="max",interval=timeframe)
    lst = [str(i) for i in data.index.values]
    ddata = process_for_prediction(data)
    return(model.predict(ddata))

In [243]:
make_prediction("btc-usd","15m")

[*********************100%***********************]  1 of 1 completed

array([[0.5814966, 0.5365739]], dtype=float32)

In [244]:
def process_for_prediction(data):
    i = -1
    row = []
    data.drop("symbol",axis=1,inplace=True)   
    data = np.array(data)
    llst = [0, 1, 2, 3, 4]
    grow = []
      
    s12 = [ 
            data[i-12][0], data[i-12][1], data[i-12][2], data[i-12][3]
        ]
    s11 = [
            data[i-11][0], data[i-11][1], data[i-11][2], data[i-11][3]
        ]
    s10 = [
            data[i-10][0], data[i-10][1], data[i-10][2], data[i-10][3]
        ]
    s9 = [
            data[i-9][0], data[i-9][1], data[i-9][2], data[i-9][3]
        ]
    s8 = [
            data[i-8][0], data[i-8][1], data[i-8][2], data[i-8][3]
        ]
    s7 = [
            data[i-7][0], data[i-7][1], data[i-7][2], data[i-7][3]
        ]
    s6 = [
            data[i-6][0], data[i-6][1], data[i-6][2], data[i-6][3]
        ]
    s5 = [
            data[i-5][0], data[i-5][1], data[i-5][2], data[i-5][3]
        ]   
    s4 = [
            data[i-4][0], data[i-4][1], data[i-4][2], data[i-4][3]
        ]
    s3 = [
            data[i-3][0], data[i-3][1], data[i-3][2], data[i-3][3]
        ]
    s2 = [
            data[i-2][0], data[i-2][1], data[i-2][2], data[i-2][3]
        ]
    s1 = [
            data[i-1][0], data[i-1][1], data[i-1][2], data[i-1][3]
        ]
        

    s1 = scaler(np.array(s1).reshape(-1,1))
    s2 = scaler(np.array(s2).reshape(-1,1))
    s3 = scaler(np.array(s3).reshape(-1,1))
    s4 = scaler(np.array(s4).reshape(-1,1))
    s5 = scaler(np.array(s5).reshape(-1,1))
    s6 = scaler(np.array(s6).reshape(-1,1))
    s7 = scaler(np.array(s7).reshape(-1,1))
    s8 = scaler(np.array(s8).reshape(-1,1))
    s9 = scaler(np.array(s9).reshape(-1,1))
    s10 = scaler(np.array(s10).reshape(-1,1))
    s11 = scaler(np.array(s11).reshape(-1,1))
    s12 = scaler(np.array(s12).reshape(-1,1))

        

    grow = np.vstack((s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12))

    arr = np.array(grow).flatten()
    row.append(arr)

    return np.array(row)
def make_prediction(symbol,timeframe):
   tv = TvDatafeed()
   data = tv.get_hist(symbol='btcusdt',exchange='binance',interval=Interval.in_15_minute,n_bars=30)
   return model.predict(process_for_prediction(data))

In [245]:
make_prediction("s","x")

WARNING:tvDatafeed.main:you are using nologin method, data you access may be limited

array([[0.12653679, 0.8836185 ]], dtype=float32)

In [189]:
yf.download("btc-usd",period="1d",interval="15m")

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2022-04-29 00:00:00+00:00,39768.617188,39819.324219,39744.535156,39819.324219,39819.324219,155101184
2022-04-29 00:15:00+00:00,39818.046875,39832.632812,39805.539062,39807.500000,39807.500000,210554880
2022-04-29 00:30:00+00:00,39799.171875,39799.171875,39730.691406,39730.691406,39730.691406,27262976
2022-04-29 00:45:00+00:00,39726.808594,39815.062500,39704.660156,39815.062500,39815.062500,134449152
2022-04-29 01:00:00+00:00,39815.343750,39842.222656,39815.343750,39842.222656,39842.222656,17850368
2022-04-29 01:15:00+00:00,39842.445312,39881.050781,39828.148438,39874.695312,39874.695312,27033600
2022-04-29 01:30:00+00:00,39881.695312,39887.269531,39848.953125,39851.039062,39851.039062,30461952
2022-04-29 01:45:00+00:00,39848.152344,39851.574219,39790.121094,39813.488281,39813.488281,23814144
2022-04-29 02:00:00+00:00,39815.246094,39821.156250,39769.332031,39807.710938,39807.710938,72452096
2022-04-29 02:15:00+00:00,39785.300781,39785.300781,39686.406250,39687.773438,39687.773438,60198912
2022-04-29 02:30:00+00:00,39689.429688,39696.390625,39683.644531,39687.214844,39687.214844,43956224
2022-04-29 02:45:00+00:00,39689.734375,39728.207031,39533.644531,39533.644531,39533.644531,119537664
2022-04-29 03:00:00+00:00,39540.828125,39545.496094,39459.937500,39459.937500,39459.937500,91527168
2022-04-29 03:15:00+00:00,39452.703125,39460.746094,39410.058594,39454.859375,39454.859375,136159232
2022-04-29 03:30:00+00:00,39449.945312,39520.503906,39435.367188,39515.203125,39515.203125,92248064
2022-04-29 03:45:00+00:00,39520.835938,39520.835938,39475.558594,39501.593750,39501.593750,26918912
2022-04-29 04:00:00+00:00,39501.160156,39522.230469,39446.148438,39485.757812,39485.757812,122994688
2022-04-29 04:15:00+00:00,39479.625000,39479.625000,39411.878906,39469.515625,39469.515625,125196288
2022-04-29 04:30:00+00:00,39470.945312,39514.496094,39469.914062,39513.253906,39513.253906,156442624
2022-04-29 04:45:00+00:00,39515.066406,39563.062500,39515.066406,39558.078125,39558.078125,121622528
2022-04-29 05:00:00+00:00,39555.625000,39593.578125,39544.339844,39549.144531,39549.144531,115122176
2022-04-29 05:15:00+00:00,39550.539062,39604.507812,39550.539062,39602.058594,39602.058594,139198464
2022-04-29 05:30:00+00:00,39600.351562,39600.351562,39567.578125,39568.496094,39568.496094,27402240
2022-04-29 05:45:00+00:00,39571.187500,39571.187500,39507.058594,39509.949219,39509.949219,54669312
2022-04-29 06:00:00+00:00,39507.710938,39521.703125,39446.738281,39446.738281,39446.738281,108724224
2022-04-29 06:15:00+00:00,39452.433594,39503.851562,39449.324219,39503.851562,39503.851562,91738112
2022-04-29 06:30:00+00:00,39512.859375,39558.953125,39507.585938,39549.519531,39549.519531,136720384
2022-04-29 06:45:00+00:00,39552.523438,39557.648438,39507.000000,39507.000000,39507.000000,29900800
2022-04-29 07:00:00+00:00,39505.796875,39505.796875,39461.402344,39492.500000,39492.500000,70332416
2022-04-29 07:15:00+00:00,39484.097656,39510.476562,39463.605469,39510.109375,39510.109375,77676544
2022-04-29 07:30:00+00:00,39510.164062,39567.562500,39510.164062,39565.441406,39565.441406,19464192
2022-04-29 07:45:00+00:00,39564.582031,39579.617188,39557.339844,39579.304688,39579.304688,4816896
2022-04-29 08:00:00+00:00,39584.148438,39603.335938,39565.667969,39567.183594,39567.183594,19615744
2022-04-29 08:15:00+00:00,39578.773438,39578.773438,39511.476562,39511.476562,39511.476562,21184512
2022-04-29 08:30:00+00:00,39518.464844,39524.589844,39455.675781,39464.203125,39464.203125,3289088
2022-04-29 08:45:00+00:00,39461.070312,39466.074219,39426.089844,39426.089844,39426.089844,24203264
2022-04-29 09:00:00+00:00,39426.621094,39426.621094,39222.839844,39250.308594,39250.308594,61128704
2022-04-29 09:15:00+00:00,39245.160156,39245.160156,39142.648438,39206.328125,39206.328125,145348608
2022-04-29 09:30:00+00:00,39203.925781,39262.593750,39187.992188,39240.105469,39240.105469,87474176
2022-04-29 09:45:00+00:00,39241.242188,39241.242188,39158.656250,39158.656250,39158.656250,18427904
2022-04-29 10:00:00+00:00,39153.179688,39196.238281,39142.898438,39184.839844,39184.839844,90193920
2022-04-29 10:15:00+00:00,39175.621094,39213.609375,39139.359375,39139.359375,39139.359375,32251904
2022-04-29 10:30:00+00:00,39131.773438,39158.152344,39064.945312,39064.945312,39064.945312,107417600
2022-04-29 10:45:00+00:00,39031.488281,39031.488281,38811.066406,38825.714844,38825.714844,426651648
2022-04-29 11:00:00+00:00,38813.449219,38887.226562,38813.449219,38875.359375,38875.359375,253132800
2022-04-29 11:15:00+00:00,38867.136719,38867.136719,38796.093750,38824.359375,38824.359375,92950528
2022-04-29 11:30:00+00:00,38821.121094,38821.121094,38698.156250,38700.589844,38700.589844,216748032
2022-04-29 11:45:00+00:00,38713.660156,38822.730469,38713.660156,38783.640625,38783.640625,263098368
2022-04-29 12:00:00+00:00,38778.386719,38794.308594,38715.925781,38794.308594,38794.308594,84611072
2022-04-29 12:15:00+00:00,38808.703125,38968.039062,38808.703125,38937.191406,38937.191406,217939968
2022-04-29 12:30:00+00:00,38946.589844,38953.164062,38902.101562,38953.164062,38953.164062,169455616
2022-04-29 12:45:00+00:00,39063.734375,39077.039062,38946.929688,38946.929688,38946.929688,192315392
2022-04-29 12:59:00+00:00,38943.148438,38943.148438,38943.148438,38943.148438,38943.148438,0