In [2]:
!pip install yfinance
!pip install yahooquery
from yahooquery import Screener
import yfinance as yf   
import pandas as pd
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,LSTM
from tensorflow.keras.layers import Dropout
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import NearestCentroid
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
import tensorflow as tf
from sklearn.tree import DecisionTreeClassifier
from sys import getsizeof
from datetime import datetime
from numpy import array

Collecting yfinance
  Downloading yfinance-0.1.70-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.10)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.5)
Collecting lxml>=4.5.1
  Downloading lxml-4.8.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.4 MB)
     |████████████████████████████████| 6.4 MB 5.1 MB/s
Collecting requests>=2.26
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 1.3 MB/s
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Installing collected packages: requests, lxml, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Attempting uninstall: lxml
    Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
Successfully installed lxml-4.8.0 requests-2.27.1 yfinance-0.1.70
Collecting yahooquery
  Downloading yahooquery-2.2.15-py2.py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 2.4 MB/s
Requirement already satisfied: lxml>=4.6.2 in /usr/local/lib/python3.7/dist-packages (from yahooquery) (4.8.0)
Requirement already satisfied: tqdm>=4.54.1 in /usr/local/lib/python3.7/dist-packages (from yahooquery) (4.64.0)
Collecting requests-futures>=1.0.0
  Downloading requests_futures-1.0.0-py2.py3-none-any.whl (7.4 kB)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yahooquery) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yahooquery) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yahooquery) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yahooquery) (1.21.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yahooquery) (1.15.0)
Requirement already satisfied: requests>=1.2.0 in /usr/local/lib/python3.7/dist-packages (from requests-futures>=1.0.0->yahooquery) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=1.2.0->requests-futures>=1.0.0->yahooquery) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=1.2.0->requests-futures>=1.0.0->yahooquery) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=1.2.0->requests-futures>=1.0.0->yahooquery) (2.10)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=1.2.0->requests-futures>=1.0.0->yahooquery) (2.0.12)
Installing collected packages: requests-futures, yahooquery
Successfully installed requests-futures-1.0.0 yahooquery-2.2.15

In [3]:
clmns = ['12 Open', '12 High', '12 Low', '12 Close', '12 Volume', '11 Open', '11 High', '11 Low', '11 Close', '11 Volume', '10 Open', '10 High', '10 Low', '10 Close', '10 Volume', '9 Open', '9 High', '9 Low', '9 Close', '9 Volume', '8 Open', '8 High', '8 Low', '8 Close', '8 Volume', '7 Open', '7 High', '7 Low', '7 Close', '7 Volume', '6 Open', '6 High', '6 Low', '6 Close', '6 Volume', '5 Open', '5 High', '5 Low', '5 Close', '5 Volume', '4 Open', '4 High', '4 Low', '4 Close', '4 Volume', '3 Open', '3 High', '3 Low', '3 Close', '3 Volume', '2 Open', '2 High', '2 Low', '2 Close', '2 Volume', '1 Open', '1 High', '1 Low', '1 Close', '1 Volume',"suggestion"]
clmnswn = ['12 Open', '12 High', '12 Low', '12 Close', '12 Volume', '11 Open', '11 High', '11 Low', '11 Close', '11 Volume', '10 Open', '10 High', '10 Low', '10 Close', '10 Volume', '9 Open', '9 High', '9 Low', '9 Close', '9 Volume', '8 Open', '8 High', '8 Low', '8 Close', '8 Volume', '7 Open', '7 High', '7 Low', '7 Close', '7 Volume', '6 Open', '6 High', '6 Low', '6 Close', '6 Volume', '5 Open', '5 High', '5 Low', '5 Close', '5 Volume', '4 Open', '4 High', '4 Low', '4 Close', '4 Volume', '3 Open', '3 High', '3 Low', '3 Close', '3 Volume', '2 Open', '2 High', '2 Low', '2 Close', '2 Volume', '1 Open', '1 High', '1 Low', '1 Close', '1 Volume']
def read_syms_from_txt():  
  with open("syms.txt","r") as f:
    lines = f.readlines()
    f.close()
  lst = []
  for line in lines:
    line = line.strip()
    lst.append(line)
  symbols = lst
  return symbols
def get_crypto_syms():
   #'all_cryptocurrencies_au','all_cryptocurrencies_ca','all_cryptocurrencies_eu','all_cryptocurrencies_gb','all_cryptocurrencies_in',
   screens = [
   'all_cryptocurrencies_us','all_cryptocurrencies_au','all_cryptocurrencies_ca','all_cryptocurrencies_eu','all_cryptocurrencies_gb','all_cryptocurrencies_in',]
   s = Screener()
   symbols = []
   for i in screens:
      data = s.get_screeners(i, count=250)
      dicts = data[i]['quotes']
      syms = [d['symbol'] for d in dicts]
      for sym in syms:
        symbols.append(sym)
   #print(len(symbols))
   #pieces = 15
   # new_arrays = np.array_split(symbols, pieces)
   return symbols
def spliting(data):
  X = data.drop(["suggestion"],axis=1)
  y = data["suggestion"]
  xTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size=0.1)
  print(xTrain.shape,end=" ")
  print(yTrain.shape)
  print(xTest.shape,end=" ")
  print(yTest.shape)
  return xTrain, xTest, yTrain, yTest
def extract_data(df):
    rows = []
    for each in range(15,df.shape[0]-1):
        sugg = 0
        if df[each][3] > df[each][0]:
          sugg = 1
        row = [
                df[each-12][0],
                df[each-12][1],
                df[each-12][2],
                df[each-12][3],
                df[each-12][4],
                df[each-11][0],
                df[each-11][1],
                df[each-11][2],
                df[each-11][3],
                df[each-11][4],
                df[each-10][0],
                df[each-10][1],
                df[each-10][2],
                df[each-10][3],
                df[each-10][4],
                df[each-9][0],
                df[each-9][1],
                df[each-9][2],
                df[each-9][3],
                df[each-9][4],
                df[each-8][0],
                df[each-8][1],
                df[each-8][2],
                df[each-8][3],
                df[each-8][4],
                df[each-7][0],
                df[each-7][1],
                df[each-7][2],
                df[each-7][3],
                df[each-7][4],
                df[each-6][0],
                df[each-6][1],
                df[each-6][2],
                df[each-6][3],
                df[each-6][4],
                df[each-5][0],
                df[each-5][1],
                df[each-5][2],
                df[each-5][3],
                df[each-5][4],
                df[each-4][0],
                df[each-4][1],
                df[each-4][2],
                df[each-4][3],
                df[each-4][4],
                df[each-3][0],
                df[each-3][1],
                df[each-3][2],
                df[each-3][3],
                df[each-3][4],
                df[each-2][0],
                df[each-2][1],
                df[each-2][2],
                df[each-2][3],
                df[each-2][4],
                df[each-1][0],
                df[each-1][2],
                df[each-1][1],
                df[each-1][3],
                df[each-1][4],
                sugg
        ]
        rows.append(row)
    return rows
def row_scaler(df):
  scaler = MinMaxScaler(feature_range=(1,10))
  last_column = df.iloc[: , -1]
  df = df.drop(columns=df.columns[-1], axis=1)
  scaled = pd.DataFrame(scaler.fit_transform(df.T).T,dtype=object,columns=clmnswn)
  scaled["suggestion"] = last_column
  return scaled
def column_scaler(df):
  scaler = MinMaxScaler(feature_range=(0,1))
  last_column = df.iloc[: , -1]
  df = df.drop(columns=df.columns[-1], axis=1)
  df_scaled = scaler.fit_transform(df.to_numpy())
  df_scaled = pd.DataFrame(df_scaled)
  df_scaled["suggestion"] = last_column
  return df_scaled
def stick_dfs(dfs):
  dataframe = dfs[0]
  for i in range(1,len(dfs)):
     dataframe = pd.concat([dataframe,dfs[i]], ignore_index = True)
  dataframe = dataframe.dropna()
  dataframe = dataframe.astype(float)
  return dataframe
def process(dfs): 
   fixed_dfs = []
   for df in dfs:
      df = df.dropna()
      df = np.array(df)
      df = extract_data(df)
      df = pd.DataFrame(df,columns= clmns)
      df = row_scaler(df)
      #df = column_scaler(df)
      fixed_dfs.append(df)
   df = stick_dfs(fixed_dfs)
   return df

In [5]:
def get_data(symbols):
    dfs = []
    for symbol in symbols[:100]:
           data = yf.download(symbol,period="MAX",interval="1d",progress=False)
           if data.empty :
             print("Passing...")
           else:
               dfs.append(data)
    ndfs = dfs
    dfs = []
    for df in ndfs:
        if df.shape[0] > 14:
          dfs.append(df)
    ndfs = []
    data = process(dfs)
    xTrain, xTest, yTrain, yTest = spliting(data)
    return xTrain, xTest, yTrain, yTest,data


#symbols = ["MSFT","AAPL","GOOG","TSLA","AMZN"]
#symbols = ["BTC-USD","LTC-USD","TRX-USD","XRP-USD","ETH-USD","BNB-USD","DASH-USD","VET-USD","LINK-USD","ADA-USD","DOT-USD","SOL-USD","BCH-USD","FTT-USD","FIL-USD","XMR-USD"]
#symbols = ["AAPL","MSFT","TSLA","GOOG"]
#symbols = ["BTC-USD","ETH-USD"]
#symbols = ["BTC-USD"]
symbols = read_syms_from_txt()
#symbols = get_crypto_syms()

#pieces = 20
#new_arrays = np.array_split(symbols, pieces)
#for symbols in new_arrays:
xTrain, xTest, yTrain, yTest,data = get_data(symbols)
data.to_parquet("MPD_v01.parquet")

data

1 Failed download:
- PIH: No data found, symbol may be delisted
Passing...

1 Failed download:
- PIHPP: No data found, symbol may be delisted
Passing...

1 Failed download:
- FCCY: No data found, symbol may be delisted
Passing...

1 Failed download:
- JFK: No data found, symbol may be delisted
Passing...

1 Failed download:
- JFKKR: No data found, symbol may be delisted
Passing...

1 Failed download:
- JFKKU: No data found, symbol may be delisted
Passing...

1 Failed download:
- JFKKW: No data found, symbol may be delisted
Passing...

1 Failed download:
- ACIA: No data found, symbol may be delisted
Passing...

1 Failed download:
- ACAM: No data found, symbol may be delisted
Passing...

1 Failed download:
- ACAMU: No data found, symbol may be delisted
Passing...

1 Failed download:
- ACAMW: No data found, symbol may be delisted
Passing...

1 Failed download:
- ACCP: No data found for this date range, symbol may be delisted
Passing...

1 Failed download:
- XLRN: No data found, symbol may be delisted
Passing...

1 Failed download:
- ACLL: No data found, symbol may be delisted
Passing...

1 Failed download:
- ADMS: No data found, symbol may be delisted
Passing...

1 Failed download:
- ADRO: No data found, symbol may be delisted
Passing...

1 Failed download:
- AEGN: No data found, symbol may be delisted
Passing...

1 Failed download:
- ARPO: No data found, symbol may be delisted
Passing...
(256806, 60) (256806,)
(28534, 60) (28534,)

,12 Open,12 High,12 Low,12 Close,12 Volume,11 Open,11 High,11 Low,11 Close,11 Volume,...,2 High,2 Low,2 Close,2 Volume,1 Open,1 High,1 Low,1 Close,1 Volume,suggestion
0,6.469477,8.780455,6.081686,6.750341,6.750341,6.784834,9.455516,6.193540,9.322475,9.322475,...,4.355597,1.438543,1.946071,1.946071,1.822884,1.000000,2.044620,1.473035,1.473035,1.0
1,6.784834,9.455516,6.193540,9.322475,9.322475,9.721599,10.000000,8.844511,8.888858,8.888858,...,2.044620,1.000000,1.473035,1.473035,1.817958,1.315357,2.542295,2.483164,2.483164,1.0
2,9.721599,10.000000,8.844511,8.888858,8.888858,9.179578,9.529427,8.248289,8.583356,8.583356,...,2.542295,1.315357,2.483164,2.483164,2.424035,2.335340,5.055297,4.124008,4.124008,0.0
3,9.630850,10.000000,8.648181,9.001734,9.001734,8.856154,9.513866,8.710572,8.913347,8.913347,...,5.279030,2.409012,4.296361,4.296361,4.634315,3.038128,5.216639,3.729636,3.729636,0.0
4,9.304733,10.000000,9.150839,9.365192,9.365192,9.733435,9.733435,5.886107,6.050992,6.050992,...,5.457405,3.154503,3.885496,3.885496,3.687633,3.138015,4.385649,3.440305,3.440305,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285335,5.289719,6.887853,4.869157,6.214949,5.233143,6.130843,6.130843,4.785051,5.205605,4.232735,...,6.130843,2.934582,3.271031,3.271031,2.934582,1.000000,2.934582,1.084114,1.084114,0.0
285336,6.839695,6.839695,5.740460,6.083966,5.289332,6.083966,6.427479,5.603052,5.946565,5.153143,...,4.229008,2.648853,2.717557,2.717557,2.648853,1.000000,3.335878,2.442748,2.442748,1.0
285337,6.083966,6.427479,5.603052,5.946565,5.153143,6.152670,7.595418,5.946565,7.458017,6.651222,...,3.335878,1.000000,2.442748,2.442748,2.648853,2.374044,3.954200,2.854964,2.854964,0.0
285338,6.152670,7.595418,5.946565,7.458017,6.651222,7.732826,8.351141,6.427479,8.213739,7.400255,...,3.954200,2.374044,2.854964,2.854964,2.717557,1.824426,3.679391,2.099235,2.099235,0.0
285339,7.732826,8.351141,6.427479,8.213739,7.400255,8.625949,10.000000,8.625949,9.450382,8.625956,...,3.679391,1.824426,2.099235,2.099235,2.992366,2.236643,3.748088,2.374044,2.374044,0.0

In [6]:
model = Sequential()


model.add(Dense(1000, activation='relu', input_shape=(xTrain.shape[1],)))
model.add(Dense(1000, activation='relu'))
model.add(Dense(1000, activation='relu'))



model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer="adam", loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 1000)              61000

 dense_1 (Dense)             (None, 1000)              1001000

 dense_2 (Dense)             (None, 1000)              1001000

 dense_3 (Dense)             (None, 1)                 1001

=================================================================
Total params: 2,064,001
Trainable params: 2,064,001
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model.fit(xTrain,yTrain,epochs=50,batch_size=64,validation_data=(xTest,yTest))

Epoch 1/50
2909/4013 [====================>.........] - ETA: 33s - loss: 0.6774 - accuracy: 0.5842

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

data = pd.read_csv("/content/drive/MyDrive/Colab Files/BinaryTest_v10_hourtesting.csv")
data = data.drop("Unnamed: 0",axis=1)
xTrain, xTest, yTrain, yTest = spliting(data)
data

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

In [5]:
import os
files = os.listdir("/content/drive/MyDrive/Colab Files/")

In [ ]:
data = pd.DataFrame()

for i in files:
    address = f"/content/drive/MyDrive/Colab Files/{i}"
    df = pd.read_parquet(address)
    data = pd.concat([data,df])
    break

data 
xTrain, xTest, yTrain, yTest = spliting(data)